#!/usr/bin/env bash
# Bring up the demo household and fill it with sample data.
#
#   deploy/demo-up.sh              # up + seed (safe to re-run)
#   deploy/demo-up.sh --reseed     # re-run the seed only
#   deploy/demo-up.sh --fresh      # destroy the demo's data first, then up + seed
#
# Generates deploy/.env.demo with fresh throwaway secrets on first run.
# .env.demo is git-ignored (/deploy/.env* in .gitignore) — the demo's secrets
# are generated, never committed.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
compose_file="$here/compose.demo.yml"
env_file="$here/.env.demo"
compose=(docker compose -f "$compose_file" --env-file "$env_file")

reseed_only=false
fresh=false
for arg in "$@"; do
  case "$arg" in
    --reseed) reseed_only=true ;;
    --fresh)  fresh=true ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

rand() { node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))'; }

load_env() {
  set -a
  # shellcheck disable=SC1090
  . "$env_file"
  set +a
}

set_env_value() {
  node - "$env_file" "$1" "$2" <<'NODE'
const [file, name, value] = process.argv.slice(2);
const fs = require('node:fs');
let text = fs.readFileSync(file, 'utf8');
const line = `${name}=${value}`;
const pattern = new RegExp(`^${name}=.*$`, 'm');
if (pattern.test(text)) text = text.replace(pattern, line);
else text += `${text.endsWith('\n') ? '' : '\n'}${line}\n`;
fs.writeFileSync(file, text);
NODE
}

wait_healthy() {
  echo "==> waiting for services to report healthy: $*"
  deadline=$(( $(date +%s) + 300 ))
  while :; do
    unhealthy=""
    for svc in "$@"; do
      cid="$("${compose[@]}" ps -q "$svc" 2>/dev/null || true)"
      if [ -z "$cid" ]; then unhealthy="$unhealthy $svc(missing)"; continue; fi
      state="$(docker inspect -f '{{.State.Health.Status}}' "$cid" 2>/dev/null || echo unknown)"
      [ "$state" = "healthy" ] || unhealthy="$unhealthy $svc($state)"
    done
    [ -z "$unhealthy" ] && break
    if [ "$(date +%s)" -ge "$deadline" ]; then
      echo "!! timed out waiting for:$unhealthy" >&2
      "${compose[@]}" ps >&2
      exit 1
    fi
    sleep 3
  done
  echo "    healthy: $*"
}

ensure_kith_key() {
  load_env
  echo "==> ensuring Heorth has a demo KithLedger household key"
  if [ -n "${KITH_API_KEY:-}" ]; then
    if KITH_URL=http://localhost:24002 node - <<'NODE' >/dev/null 2>&1
const base = process.env.KITH_URL;
const key = process.env.KITH_API_KEY;
(async () => {
  const res = await fetch(`${base}/api/v1/reminders?limit=1`, {
    headers: { authorization: `Bearer ${key}` },
  });
  process.exit(res.ok ? 0 : 1);
})().catch(() => process.exit(1));
NODE
    then
      echo "    existing demo household key is valid"
      return
    fi
    echo "    existing demo key is not valid for this data volume; minting a new one"
  fi

  new_key="$(
    KITH_URL=http://localhost:24002 node - <<'NODE'
const base = process.env.KITH_URL;
const password = process.env.KITH_ADMIN_PASSWORD;
const post = (path, body, token) => fetch(`${base}${path}`, {
  method: 'POST',
  headers: {
    'content-type': 'application/json',
    ...(token ? { authorization: `Bearer ${token}` } : {}),
  },
  body: JSON.stringify(body),
});
(async () => {
  const login = await post('/api/v1/auth/token', {
    email: 'admin@kithledger.local',
    password,
  });
  if (!login.ok) throw new Error(`KithLedger admin login failed: ${login.status}`);
  const token = (await login.json()).data.token;
  const created = await post('/api/v1/auth/keys', {
    name: 'heorth-hearth-wall-demo',
    kind: 'household',
  }, token);
  if (!created.ok) throw new Error(`KithLedger key creation failed: ${created.status}`);
  process.stdout.write((await created.json()).data.key);
})().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
NODE
  )"
  set_env_value KITH_API_KEY "$new_key"
  export KITH_API_KEY="$new_key"
  echo "    minted a throwaway household key"
}

if [ ! -f "$env_file" ]; then
  echo "==> generating $env_file (throwaway demo secrets)"
  # Single-line Ed25519 JWK, per the generator documented in .env.example.
  satellite_key="$(node -e 'const{generateKeyPairSync}=require("crypto");const{privateKey}=generateKeyPairSync("ed25519");const j=privateKey.export({format:"jwk"});j.alg="EdDSA";j.kid="heorth-demo";j.use="sig";console.log(JSON.stringify(j))')"
  cat > "$env_file" <<EOF
# Wyrhta Labs DEMO environment — GENERATED by deploy/demo-up.sh.
#
# Throwaway values for a local, isolated demo household. Not a template, not
# a backup, and not related to deploy/.env. Delete this file and re-run
# demo-up.sh to rotate everything.
#
# The demo reaches no external system: M365 is pinned blank in
# compose.demo.yml, and KithLedger points only at the sibling demo container.
# KITH_API_KEY below is a throwaway household key minted by this script.

POSTGRES_SUPERUSER_PASSWORD=$(rand)
HEORTH_DB_PASSWORD=$(rand)
KITH_DB_PASSWORD=$(rand)

# All three JWT secrets MUST differ — a shared secret would make a token
# minted by one service valid at another.
HEORTH_JWT_SECRET=$(rand)
KITH_JWT_SECRET=$(rand)

# Printed by demo-up.sh at the end so you can log in.
HEORTH_ADMIN_PASSWORD=demo-admin-pw-$(node -e 'console.log(require("crypto").randomBytes(6).toString("hex"))')
KITH_ADMIN_PASSWORD=demo-admin-pw-$(node -e 'console.log(require("crypto").randomBytes(6).toString("hex"))')

HOUSEHOLD_NAME="Ashcombe Demo Household"
HEORTH_ADMIN_EMAIL=admin@demo.invalid

# Every household member the seed creates shares this password.
DEMO_MEMBER_PASSWORD=demo-member-pw

# Satellite identity (ADR 0009) — generated fresh for this demo.
SATELLITE_SIGNING_KEY=$satellite_key
SATELLITE_SIGNING_KID=heorth-demo
SATELLITE_SIGNING_ALG=EdDSA
SATELLITE_AUDIENCES=kithledger
HEORTH_JWKS_URL=http://heorth:3000/.well-known/jwks.json
SATELLITE_AUDIENCE=kithledger

JWT_TTL_SECONDS=604800
DB_POOL_MAX=10
UPSTREAM_TIMEOUT_MS=10000
EOF
  echo "    done"
fi

if [ "$fresh" = true ]; then
  echo "==> destroying the demo's containers and data volume"
  "${compose[@]}" down -v
fi

if [ "$reseed_only" = false ]; then
  echo "==> building and starting KithLedger so the demo key can be minted"
  "${compose[@]}" up -d --build db kithledger
  wait_healthy db kithledger
  ensure_kith_key

  echo "==> building and starting the full demo stack"
  "${compose[@]}" up -d --build
  wait_healthy db heorth kithledger heorth-mcp
else
  wait_healthy kithledger
  ensure_kith_key
  echo "==> refreshing Heorth with the demo KithLedger key"
  "${compose[@]}" up -d --build heorth heorth-mcp
  wait_healthy heorth heorth-mcp
fi

echo "==> seeding sample data"
load_env
HEORTH_URL=http://localhost:24000 \
KITH_URL=http://localhost:24002 \
node "$here/seed-demo.mjs"

# The member roster is READ BACK FROM HEORTH rather than repeated here, so this
# block cannot drift from what the seed actually created (or from anything added
# by hand afterwards). The maintenance admin is filtered out by its handle: it is
# not a household member and logging in as it shows an empty household.
members="$(
  HEORTH_URL=http://localhost:24000 node -e '
    const base = process.env.HEORTH_URL;
    const body = { email: process.env.HEORTH_ADMIN_EMAIL, password: process.env.HEORTH_ADMIN_PASSWORD };
    const post = (p, b, t) => fetch(base + p, {
      method: "POST",
      headers: { "content-type": "application/json", ...(t ? { authorization: `Bearer ${t}` } : {}) },
      body: JSON.stringify(b),
    }).then((r) => r.json());
    const get = (p, t) => fetch(base + p, { headers: { authorization: `Bearer ${t}` } }).then((r) => r.json());
    // Wrapped in an async IIFE: `node -e` evaluates as CommonJS, where a
    // top-level await is a syntax error.
    (async () => {
      const { data } = await post("/api/v1/auth/token", body);
      const list = (await get("/api/v1/members", data.token)).data ?? [];
      const rows = list.filter((m) => m.handle !== "admin");
      const w = Math.max(0, ...rows.map((m) => m.email.length));
      for (const m of rows) console.log(`  ${m.email.padEnd(w)}  ${m.role.padEnd(5)}  ${m.displayName}`);
    })();
  ' 2>/dev/null || true
)"
# Never fatal: the stack is already up and seeded by this point, so failing to
# pretty-print the roster must not fail the run. `|| true` above keeps the
# command substitution from tripping `set -e`.
[ -n "$members" ] || members="  (could not read the member list — see the seed summary above)"

cat <<EOF

==> demo household is up

  Heorth        http://localhost:24000    (web UI + REST at /api/v1)
  KithLedger    http://localhost:24002    (REST at /api/v1)
  heorth-mcp    http://localhost:24003    (MCP over Streamable HTTP)
  Postgres      localhost:25432           (user postgres)

  LOG IN AS A MEMBER — every one of these has the password: $DEMO_MEMBER_PASSWORD

$members

  Service accounts (no household data of their own):
    Heorth admin        $HEORTH_ADMIN_EMAIL / $HEORTH_ADMIN_PASSWORD
    KithLedger admin    admin@kithledger.local / $KITH_ADMIN_PASSWORD

  The Heorth admin is the MAINTENANCE admin: it is quarantined from owning
  household data and is stripped of any on every boot, so logging in as it
  shows an EMPTY household. Use a member above to see the seeded content.

  Reprint these logins without touching the stack:
    grep -E '^(HEORTH_ADMIN_EMAIL|HEORTH_ADMIN_PASSWORD|KITH_ADMIN_PASSWORD|DEMO_MEMBER_PASSWORD)=' deploy/.env.demo

  Tear down:  docker compose -f deploy/compose.demo.yml --env-file deploy/.env.demo down -v
EOF
